# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=30)),
                ('change', models.CharField(max_length=30)),
                ('volume', models.CharField(max_length=30)),
            ],
        ),
    ]
