# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-07 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('income', models.CharField(max_length=100)),
                ('plans', models.CharField(max_length=150)),
                ('schemes', models.CharField(max_length=50)),
                ('ex_returns', models.CharField(max_length=50)),
                ('problems_faced', models.CharField(max_length=50)),
                ('saving_ratio', models.CharField(max_length=20)),
                ('span', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('your_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('job_type', models.CharField(max_length=15)),
                ('phone_no', models.CharField(max_length=15)),
            ],
        ),
    ]
