# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-07 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0002_profile_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.AddField(
            model_name='userdata',
            name='ex_returns',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='income',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='plans',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='problems_faced',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='saving_ratio',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='schemes',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='span',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
