# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-24 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0004_extrastock'),
    ]

    operations = [
        migrations.CreateModel(
            name='mostloser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=30)),
                ('change', models.CharField(max_length=30)),
            ],
        ),
    ]
