# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-03 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0005_mostloser'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrastock',
            name='symbol',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
