# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-04 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0006_extrastock_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('income', models.BigIntegerField()),
                ('span', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=100)),
                ('ex_return', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
