# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-04 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0007_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ex_return',
            field=models.CharField(max_length=10),
        ),
    ]
