# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-05 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0008_auto_20200304_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthlyrecom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('rrate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='yearlyrecom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('rrate', models.CharField(max_length=20)),
            ],
        ),
    ]
