# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-05 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0009_monthlyrecom_yearlyrecom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlyrecom',
            name='name',
        ),
    ]
