# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-05 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0011_yearlyrecom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyrecom',
            name='name',
        ),
    ]
