# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0012_remove_monthlyrecom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrecom',
            name='stockname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
